name: 'jaffle_shop'
version: '1.0.0'

profile: 'dbt_study_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

seeds:
  jaffle_shop: 
    +database: dbt-certification-study 
    jaffle_shop: 
      +schema: raw_jaffle_shop
    stripe:
      +schema: raw_stripe

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  jaffle_shop:
    # Configurations for models under models/staging/
    staging:
      +materialized: view
      +schema: staging
      +tags:
        - "staging"

    # Configurations for models under models/marts/
    marts:
      +materialized: table
      +schema: marts
      +tags:
        - "marts"

    legacy:
      +materialized: table
      +schema: legacy
      +tags:
        - "legacy"