version: 2

sources:
  - name: main
    database: dbt-certification-study 
    schema: jaffle_shop

    tables:
      - name: raw_customers
      - name: raw_orders
      - name: raw_items
      - name: raw_products
      - name: raw_supplies
      - name: raw_stores