version: 2

sources:
  - name: main
    description: Clone of a PostGres database.
    database: dbt-certification-study 
    schema: raw

    tables:
      - name: jaffle_shop_orders
      - name: jaffle_shop_customers
      - name: stripe_payments